###############
# - Classes - #
###############

class Image:
    def __init__(self, **kwargs): ...
    
    def loadFile(self, file): ...
    def decodeBin(self, file): ...
    def decodeJpeg(self, file): ...
    def rawDecode(self, raw): ...

    def saveImage(self, saveFile): ...
    def drawImage(self, window, displayScale): ...
    
    def getSize(self): ...
    def getMatrix(self): ...
    def getAlpha(self): ...

    def setAlpha(self, alpha) -> None: ...

class Canvas:
    def __init__(self, width, height, bgcolour = [0, 0, 0]): ... 
    
    def addLine(self, position, colour, direction) -> None: ...

    def blitImage(self, img : Image, pos = [0,0], alphaOverride = None, **kwargs): ...
    
    def saveImage(self, saveFile, type = "bin") -> None: ...

    def getMatrix(self) -> list: ...
    def getSize(self) -> list: ...

    def update(self): ...
