
###############
# - Classes - #
###############

class GetAnimeList():
    def GetFull(username, refresh = False, save = True): ...
    def GetWatching(username, refresh = False, save = True): ...
    def GetDetailed(username, refresh = False, save = True): ...

class Date():
    def __init__(self, dayStr : str, timeStr : str, timeZone = "+9"): ...
    def changeTimeZone(self, timeZone): ...
    def GetTime(self): ...
    def GetDay(self): ...


#################
# - Functions - #
#################

def CheckCache(key, file): ...
def SaveResult(data, fileName = "DefaultSave.json", saveType = "Replace"): ...
def SendRequest(endpoint = "", fields = {}, headers = {}, URLOveride = None): ...
def GetAnimeInfo(id, refresh = False, save = True): ...
def GetMangaInfo(id, refresh = False, save = True, returnFields = None): ...
def GetUserFavourites(user, refresh = False, save = False): ...


######################
# - Auth Functions - #
######################

def GetCodeVerifier(): ...
def GetAuthURL(codeVerifier, clientID): ...
def CompleteAuth(code, codeVerifier): ...
