
class StackedBarChart:
    def __init__(self, xLabel : str, yLabel : str, layers : list) -> None: ...
    def AddColumn(self, label : str, data : list = None) -> None: ...
    def AddLayer(self, layerName : str, defaultValue : int = 0) -> None: ...
    def ModifyColumn(self, columnName : str, data : list) -> None: ...
    def GetColumn(self, columnName : str) -> list: ...
    def GetColumnLabels(self) -> list: ...
    def GetLayers(self) -> list: ...
    def SetColours(self, colours : dict) -> None: ...
    def Draw(self, order : list = None) -> None: ...
    def OrderColumns(self, sortKeys : list = ["total"]) -> list: ...
